sudo: required
dist: precise
group: edge

language: java
jdk:
  - oraclejdk8

# whitelist
branches:
  only:
    - dev
  except:
    - v-dev

# add support for go, and python as well
before_install:  
 # install go 1.5.2
 - wget https://storage.googleapis.com/golang/go1.5.2.linux-amd64.tar.gz
 - tar -C /usr/local -xzf go1.5.2.linux-amd64.tar.gz
 - export GOROOT=/usr/local/go
 - export PATH=$GOROOT/bin:$PATH
 # install python 
 - add-apt-repository ppa:fkrull/deadsnakes
 - apt-get update
 - apt-get install python2.7

install:
  - make all

script: make test_java

cache:
  directories:
    - $HOME/.m2
    - /usr/bin

before_deploy:
  # Clean the v-dev release and tag we are using to release development version in CI
  - sudo wget https://github.com/benchflow/benchflow/raw/dev/ci/clean_v-dev_release.sh -O /usr/bin/clean_v-dev_release.sh
  - sudo chmod +x /usr/bin/clean_v-dev_release.sh
  - export REPO_NAME=commons
  - /usr/bin/clean_v-dev_release.sh

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_ACCESS_TOKEN
  file: 
    - keyname-hash-generator/java/target/benchflow-keyname-hash-generator.jar
  skip_cleanup: true
  on:
    tags: false
    repo: benchflow/commons
    branch: dev
